name: medrocket_home_task_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  some_form_repository:
    path: some_form_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_lint: ^0.1.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
